### ISSUE TITLE
App key  not in this cluster. Did you forget to specify the cluster?

### ISSUE THREAD

**Issue by Valentine-Mario** [WillSewell/pusher-http-rust#24]
Had this error **App key  not in this cluster. Did you forget to specify the cluster?** when I tried to send a message over pusher.
Below is my config

 ```
let pusher = PusherBuilder::new("ID", "KEY", "SECRET").finalize();
  pusher.trigger("test_channel", "my_event", "test message").await.unwrap();
```

**Comment by benw-pusher** [comment]
I assume you have supplied the app ID, key and secrets instead of the placeholders? 
If your app is in a cluster other than mt1 then you will need to specify this as below:


`let pusher = Pusher::new("id", "key", "secret").cluster("cluster").finalize();`

**Comment by Valentine-Mario** [comment]
Yes I supplied the appropriate credentials. 

But I got the following:
Pusher::new is not a valid method and there is no method called cluster on the pusher builder,

**Comment by benw-pusher** [comment]
Ah apologies, the code I shared has not been merged. 
To confirm - is your app in the mt1 cluster?

**Comment by Valentine-Mario** [comment]
No it isn't. It's eu

The struct properties for both the Pusher and PuserBuilder is as follows
```

{pub app_id: String,
    pub key: String,
    pub secret: String,
    pub host: String,
    pub secure: bool,
    pub http_client: Client<C>,
}
```

There isn't any field for cluster

**Comment by benw-pusher** [comment]
You may be able to workaround this using the suggestion provided in https://github.com/pusher-community/pusher-http-rust/issues/9, however this appears to have some limitations. 

I'll raise a note internally to add cluster support to the library - however as this is a community library we can't commit to a delivery or delivery time.

**Comment by Valentine-Mario** [comment]
Thanks. The solution using the url builder worked fine.

**Comment by ta3pks** [comment]
@benw-pusher after 2 years this doesnt seem to be fixed which seems a relatively easy fix.
Is the project dead and should it be forked ?

**Comment by WillSewell** [comment]
I'm not actively working on it, but would welcome contributions.

**Comment by ta3pks** [comment]
a lot of stuff that are in master have not been published to crates.io I would be glad to contribute but i think first the lib should be syncronized before anybody can actually contribute. That is why i asked to understand whether to create a new fork and publish under different name or contribute here
