### ISSUE TITLE
Remove "debug" prints

### ISSUE THREAD

**Issue by flavray** [WillSewell/pusher-http-rust#3]
Hi,

I'm using your library to interact with Pusher, while testing I've noted that you left some kind of debug print in your code, here:
https://github.com/pusher-community/pusher-http-rust/blob/4d7171381d07303cc7c9405a55a704939a91ebb4/src/request.rs#L39

Would it be possible possible to fix this?

Thanks :)

**Comment by jpatel531** [comment]
no problem!

**Comment by jpatel531** [comment]
0.1.4 released :)

**Comment by flavray** [comment]
Great, thanks ! o/
